import { plain, type CuratedPassage, type CuratedQuestion } from "./shared";

const PARAGRAPHS = ["A", "B", "C", "D", "E", "F", "G"];

function locate(
  prompt: string,
  answer: string,
  supporting_sentence: string,
  explanation: string,
): CuratedQuestion {
  return {
    ...plain("matching_information", prompt, answer, supporting_sentence, explanation),
    options: PARAGRAPHS,
  };
}

function gap(
  prompt: string,
  answer: string,
  supporting_sentence: string,
  explanation: string,
): CuratedQuestion {
  return {
    ...plain("summary_completion", prompt, answer, supporting_sentence, explanation),
    word_limit: "ONE WORD ONLY",
  };
}

const EVACUATION_STEM =
  "Which TWO of the following statements about the evacuation of the manuscripts are made in the passage?";
const EVACUATION_OPTIONS = [
  "It was organised and paid for by the national government.",
  "The manuscripts were moved in small quantities to avoid attention.",
  "Every manuscript in the city was carried to safety.",
  "Some manuscripts were burned as the armed groups withdrew.",
  "Most of the manuscripts were transported to the capital by plane.",
];

function evacuation(supporting_sentence: string, explanation: string): CuratedQuestion {
  return {
    ...plain("multiple_choice", EVACUATION_STEM, "B or D", supporting_sentence, explanation),
    options: EVACUATION_OPTIONS,
  };
}

export const TIMBUKTU_MANUSCRIPTS: CuratedPassage = {
  key: "timbuktu-manuscripts",
  title: "The Manuscripts of Timbuktu",
  topic: "a desert city of scholars and the rescue of its books",
  difficulty: 6,
  body: `A) For centuries, the name Timbuktu stood in the European imagination for somewhere impossibly remote. In English, the phrase "from here to Timbuktu" came to mean a journey to the very end of the world, and many people were unsure whether the city existed at all. Its reputation for wealth nevertheless reached Europe, where one fourteenth-century map showed a West African king holding a large piece of gold. Yet the real Timbuktu, on the southern edge of the Sahara in present-day Mali, was anything but isolated. For several hundred years it was a busy commercial crossroads and one of the most important centres of learning in the Islamic world.

B) The city's early growth owed everything to its location. Timbuktu lies a few kilometres from the River Niger, at the point where the desert meets the more fertile lands to the south. This made it a natural meeting point for traders: camel caravans arriving from North Africa could exchange their goods with merchants who travelled by boat along the river. Salt from desert mines was carried south, while gold, ivory and grain moved north. Salt was so valuable that it was sometimes exchanged for gold, and the wealth generated by this trade allowed the city to expand rapidly.

C) By the fifteenth and sixteenth centuries, Timbuktu had entered a golden age. Its mosques became places of study, attracting thousands of students from across West Africa and beyond. Scholars taught law, theology, astronomy, mathematics and medicine, and learned men were treated with great respect. Books became some of the most valuable goods sold in the markets. Because every copy had to be written by hand, professional copyists were in constant demand, and wealthy families competed to build collections of rare works.

D) The manuscripts that survive from this period reveal an extraordinarily varied intellectual life. Some are works of astronomy that describe the movements of the stars, while others record medical treatments or explain how to calculate the dates of religious festivals. Alongside these scholarly texts are more ordinary documents: commercial contracts, letters between merchants and legal judgements settling disputes over property and debt. Most were written in Arabic, but some use Arabic script to record local African languages, and many are decorated with coloured inks and elaborate borders.

E) The golden age did not last. After an invasion from Morocco at the end of the sixteenth century, Timbuktu's importance declined, and trade routes gradually shifted towards the coast. Many of the city's books left with the invaders, but a great number remained. Over the following centuries, they were kept in private family libraries, passed down from one generation to the next. Families stored them in wooden chests or even buried them to protect them from theft. Keeping them safe was a constant struggle, since termites, dust and humidity could destroy fragile paper within a few years. In the twentieth century, a public institute was established in the city to collect and conserve the manuscripts, and several families opened their own collections to researchers.

F) In 2012 the manuscripts faced a new danger when armed groups took control of Timbuktu. Fearing that the documents would be destroyed, local librarians and their helpers organised a secret evacuation. Over several months they packed manuscripts into metal trunks and rice sacks and carried them in small quantities by road and by river to the capital, Bamako, hoping not to attract attention at checkpoints. When the occupiers withdrew in early 2013, they set fire to a number of manuscripts that had been left in a library building. Several thousand documents were lost, but the great majority had already been carried to safety.

G) The rescue created problems of its own. The air in Bamako is far more humid than the dry desert climate of Timbuktu, and some manuscripts have since shown signs of mould. Conservation teams have responded by building climate-controlled storage and by photographing thousands of pages, so that the texts can be studied online without the originals being handled. Only a small fraction of the collections has yet been translated, and many of the families who guarded them for generations hope that the manuscripts will one day return home. Scholars believe the texts will continue to challenge the outdated idea that African societies relied on spoken rather than written history.`,
  questions: [
    locate(
      "a reference to a phrase once used to describe a very distant place",
      "A",
      'In English, the phrase "from here to Timbuktu" came to mean a journey to the very end of the world, and many people were unsure whether the city existed at all.',
      "Paragraph A explains the English phrase 'from here to Timbuktu', meaning the end of the world.",
    ),
    locate(
      "examples of everyday documents found among the manuscripts",
      "D",
      "Alongside these scholarly texts are more ordinary documents: commercial contracts, letters between merchants and legal judgements settling disputes over property and debt.",
      "Paragraph D lists 'more ordinary documents' such as contracts and letters. Paragraph C mentions books too, but not everyday documents.",
    ),
    locate(
      "a description of the containers in which the manuscripts were smuggled out",
      "F",
      "Over several months they packed manuscripts into metal trunks and rice sacks and carried them in small quantities by road and by river to the capital, Bamako, hoping not to attract attention at checkpoints.",
      "Paragraph F names the 'metal trunks and rice sacks'. The 'wooden chests' in E are for storage at home, not smuggling — a deliberate trap.",
    ),
    locate(
      "a mention of a problem caused by the difference in climate between two cities",
      "G",
      "The air in Bamako is far more humid than the dry desert climate of Timbuktu, and some manuscripts have since shown signs of mould.",
      "Paragraph G contrasts humid Bamako with dry Timbuktu and the mould that resulted.",
    ),
    locate(
      "an explanation of why the city became a place where traders met",
      "B",
      "This made it a natural meeting point for traders: camel caravans arriving from North Africa could exchange their goods with merchants who travelled by boat along the river.",
      "Paragraph B links the city's position between desert and river to its role as a 'natural meeting point for traders'.",
    ),
    gap(
      "In its golden age, the city's mosques drew thousands of ______ from across West Africa.",
      "students",
      "Its mosques became places of study, attracting thousands of students from across West Africa and beyond.",
      "The mosques attracted 'thousands of students'.",
    ),
    gap(
      "Scholars there taught subjects such as law, astronomy, mathematics and ______.",
      "medicine",
      "Scholars taught law, theology, astronomy, mathematics and medicine, and learned men were treated with great respect.",
      "'Medicine' completes the list. 'Theology' is also in the list but is not the missing item, because the summary leaves it out.",
    ),
    gap(
      "Since every book was written by hand, professional ______ were always needed.",
      "copyists",
      "Because every copy had to be written by hand, professional copyists were in constant demand, and wealthy families competed to build collections of rare works.",
      "'In constant demand' is paraphrased as 'always needed'.",
    ),
    gap(
      "After the city declined, many manuscripts were kept in private family ______.",
      "libraries",
      "Over the following centuries, they were kept in private family libraries, passed down from one generation to the next.",
      "They were kept in 'private family libraries'.",
    ),
    gap(
      "To protect them from theft, families kept them in wooden ______ or buried them.",
      "chests",
      "Families stored them in wooden chests or even buried them to protect them from theft.",
      "The families used 'wooden chests'.",
    ),
    gap(
      "Termites, dust and ______ could destroy the fragile paper within a few years.",
      "humidity",
      "Keeping them safe was a constant struggle, since termites, dust and humidity could destroy fragile paper within a few years.",
      "The third threat in the list is 'humidity'.",
    ),
    evacuation(
      "Over several months they packed manuscripts into metal trunks and rice sacks and carried them in small quantities by road and by river to the capital, Bamako, hoping not to attract attention at checkpoints.",
      "B is correct: they moved the manuscripts 'in small quantities' so as 'not to attract attention'. A is wrong — local librarians organised it. E is wrong — they went 'by road and by river', not by plane.",
    ),
    evacuation(
      "When the occupiers withdrew in early 2013, they set fire to a number of manuscripts that had been left in a library building.",
      "D is correct: the occupiers 'set fire to a number of manuscripts' as they withdrew. C is wrong because 'several thousand documents were lost'.",
    ),
  ],
};
