import "server-only";

import { createAdminClient } from "@/lib/supabase/admin";

import { lessonContentSchema, type LessonContent } from "./types";

/**
 * One lesson, for a stranger holding a link.
 *
 * WHY THIS BYPASSES RLS, DELIBERATELY. The visitor has no session, so there is
 * no `auth.uid()` for a policy to reason about — the only thing they present is
 * the token itself, and the token IS the credential. The obvious alternative,
 * an anon policy of `using (share_enabled)`, is worse than it looks: it would
 * let anyone with the anon key list EVERY shared lesson on the platform, across
 * every centre, because a policy cannot require that the caller already knew
 * which row they were asking for. Narrowing it here — service role, exact token
 * match, `share_enabled` asserted in the same query — grants exactly one row to
 * someone who already had its unguessable name.
 *
 * The two conditions are in one `.eq()` chain rather than checked afterwards on
 * purpose: a revoked share must not be readable even for the instant between
 * fetching and testing, and a filter that runs in Postgres cannot be forgotten
 * by a later edit the way an `if` can.
 *
 * What comes back is deliberately thin. No brief (the teacher's own words are
 * not the reader's business), no org, no author, no ids beyond the lesson's own
 * — a public page should carry the lesson and nothing about the institution
 * behind it.
 */
export interface SharedLesson {
  id: string;
  title: string;
  level: string | null;
  language: string;
  content: LessonContent;
}

export async function loadSharedLesson(token: string): Promise<SharedLesson | null> {
  const clean = (token || "").trim();
  // A token is generated by `secrets.token_urlsafe`; anything with the wrong
  // shape is a probe, and answering it with a database round trip is a
  // courtesy it has not earned.
  if (!clean || clean.length < 16 || clean.length > 128 || !/^[A-Za-z0-9_-]+$/.test(clean)) {
    return null;
  }

  const supabase = createAdminClient();
  const { data } = await supabase
    .from("lessons")
    .select("id, title, level, explain_language, content, status")
    .eq("share_token", clean)
    .eq("share_enabled", true)
    .maybeSingle();

  if (!data) return null;
  // An archived lesson keeps its token so the same link works again if it is
  // restored, but it should not answer while it is put away.
  if (data.status === "archived") return null;

  const parsed = lessonContentSchema.safeParse(data.content);
  if (!parsed.success) return null;

  return {
    id: data.id as string,
    title: data.title as string,
    level: (data.level as string | null) ?? null,
    language: (data.explain_language as string) ?? "en",
    content: parsed.data as LessonContent,
  };
}
