/**
 * Academic Writing Task 1 reports for the curated practice set (see
 * ../starter-set). Each carries the figure the studio draws and the grader reads.
 *
 * Built on the SHAPE of the real exam (CLAUDE.md §IP): line graphs over time,
 * some with projections; single and grouped bar charts; pie charts; and tables
 * with several dimensions. Every number is invented, and places are generic
 * ("Country A", "one city") so no figure reads as a real statistic about a real
 * place.
 *
 * NOT covered, because the figure pipeline cannot draw them yet: process
 * diagrams, maps and paired or mixed charts — about half of real Task 1 papers.
 * See lib/writing/figure.ts.
 *
 * Difficulty rises with what there is to select: one steady series at 5;
 * crossing lines, reversals, projections and several dimensions at 8.
 */

import type { Figure } from "@/lib/writing/figure";

import { T1_TAIL, type StarterPrompt } from "./shared";

function report(
  topic_family: string,
  difficulty: number,
  lead: string,
  figure: Figure,
): StarterPrompt {
  return {
    task_type: "task1_academic",
    category: null,
    topic_family,
    difficulty,
    prompt_text: `${lead}\n\n${T1_TAIL}`,
    figure,
  };
}

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

// ---- Line graphs -----------------------------------------------------------

const LINE: StarterPrompt[] = [
  report(
    "transport",
    5,
    "The line graph below shows the average number of passengers per day, in thousands, who used the metro system in the city of Norvale between 2012 and 2022.",
    {
      kind: "line",
      title: "Average daily metro passengers in Norvale, 2012–2022",
      unit: "k",
      x_label: "Year",
      y_label: "Passengers per day (thousands)",
      categories: ["2012", "2014", "2016", "2018", "2020", "2022"],
      series: [{ name: "Passengers", values: [310, 345, 380, 420, 190, 360] }],
    },
  ),
  report(
    "environment",
    6,
    "The line graph below shows the amount of electricity, in gigawatt hours, generated by wind and solar power in one country between 2010 and 2025.",
    {
      kind: "line",
      title: "Electricity generated by wind and solar power, 2010–2025",
      unit: "GWh",
      x_label: "Year",
      y_label: "Electricity generated (GWh)",
      categories: ["2010", "2013", "2016", "2019", "2022", "2025"],
      series: [
        { name: "Wind", values: [4, 9, 15, 22, 30, 37] },
        { name: "Solar", values: [1, 3, 7, 14, 26, 41] },
      ],
    },
  ),
  report(
    "society",
    7,
    "The line graph below shows the percentage of the population aged 65 and over in three countries between 1980 and 2020, with projections up to 2050.",
    {
      kind: "line",
      title: "Population aged 65 and over, 1980–2050 (figures from 2030 are projections)",
      unit: "%",
      x_label: "Year",
      y_label: "Share of population (%)",
      categories: ["1980", "1990", "2000", "2010", "2020", "2030", "2040", "2050"],
      series: [
        { name: "Country A", values: [11, 13, 15, 18, 21, 25, 28, 30] },
        { name: "Country B", values: [6, 7, 8, 10, 13, 17, 22, 26] },
        { name: "Country C", values: [4, 4, 5, 6, 8, 11, 14, 18] },
      ],
    },
  ),
  report(
    "work",
    8,
    "The line graph below shows the percentage of employees who worked mainly from home in four industries in one country between 2015 and 2023.",
    {
      kind: "line",
      title: "Employees working mainly from home, by industry, 2015–2023",
      unit: "%",
      x_label: "Year",
      y_label: "Employees working from home (%)",
      categories: ["2015", "2017", "2019", "2021", "2023"],
      series: [
        { name: "Technology", values: [12, 15, 19, 64, 48] },
        { name: "Finance", values: [6, 8, 10, 55, 31] },
        { name: "Education", values: [2, 2, 3, 40, 6] },
        { name: "Retail", values: [1, 1, 1, 9, 3] },
      ],
    },
  ),
  report(
    "health",
    6,
    "The line graph below shows the average number of hours of sleep per night reported by three age groups in one country between 2004 and 2024.",
    {
      kind: "line",
      title: "Average hours of sleep per night by age group, 2004–2024",
      unit: "h",
      x_label: "Year",
      y_label: "Hours per night",
      categories: ["2004", "2009", "2014", "2019", "2024"],
      series: [
        { name: "Teenagers (13–17)", values: [8.4, 8.0, 7.6, 7.1, 6.9] },
        { name: "Adults (25–54)", values: [7.3, 7.2, 7.0, 6.9, 6.8] },
        { name: "Adults (65+)", values: [6.6, 6.7, 6.9, 7.0, 7.2] },
      ],
    },
  ),
  report(
    "tourism",
    7,
    "The line graph below shows the number of visits, in thousands, to three types of attraction in a coastal region in each month of 2023.",
    {
      kind: "line",
      title: "Monthly visits to attractions in a coastal region, 2023",
      unit: "k",
      x_label: "Month",
      y_label: "Visits (thousands)",
      categories: MONTHS,
      series: [
        { name: "Beaches", values: [5, 6, 12, 25, 48, 90, 130, 125, 70, 30, 9, 6] },
        { name: "Museums", values: [22, 24, 26, 28, 30, 33, 38, 37, 31, 27, 23, 30] },
        { name: "Theme parks", values: [0, 0, 15, 32, 45, 60, 85, 88, 50, 35, 0, 0] },
      ],
    },
  ),
  report(
    "technology",
    5,
    "The line graph below shows the percentage of adults in two age groups who used online banking in one country between 2008 and 2023.",
    {
      kind: "line",
      title: "Adults using online banking, by age group, 2008–2023",
      unit: "%",
      x_label: "Year",
      y_label: "Adults using online banking (%)",
      categories: ["2008", "2011", "2014", "2017", "2020", "2023"],
      series: [
        { name: "Aged 18–40", values: [35, 52, 68, 80, 88, 92] },
        { name: "Aged 41 and over", values: [12, 20, 33, 48, 65, 74] },
      ],
    },
  ),
  report(
    "economy",
    8,
    "The line graph below shows the average price of a two-bedroom flat and the average annual salary, both in thousands of dollars, in one city between 2000 and 2024.",
    {
      kind: "line",
      title: "Average flat price and average annual salary, 2000–2024 ($ thousands)",
      x_label: "Year",
      y_label: "Thousands of dollars",
      categories: ["2000", "2004", "2008", "2012", "2016", "2020", "2024"],
      series: [
        { name: "Average two-bedroom flat price", values: [120, 165, 210, 195, 260, 340, 410] },
        { name: "Average annual salary", values: [28, 31, 35, 36, 39, 43, 47] },
      ],
    },
  ),
  report(
    "environment",
    7,
    "The line graph below shows the average amount of water, in litres, used per person per day in three cities between 1990 and 2020, with projections for 2030 and 2040.",
    {
      kind: "line",
      title: "Daily water use per person, 1990–2040 (figures from 2030 are projections)",
      unit: "L",
      x_label: "Year",
      y_label: "Litres per person per day",
      categories: ["1990", "2000", "2010", "2020", "2030", "2040"],
      series: [
        { name: "City A", values: [310, 290, 250, 210, 180, 160] },
        { name: "City B", values: [180, 195, 205, 210, 215, 220] },
        { name: "City C", values: [120, 150, 175, 190, 185, 175] },
      ],
    },
  ),
];

// ---- Bar charts ------------------------------------------------------------

const BAR: StarterPrompt[] = [
  report(
    "leisure",
    5,
    "The bar chart below shows the number of adults, in thousands, who took part in six sports at least once a month in one city in 2023.",
    {
      kind: "bar",
      title: "Adults taking part in sport at least once a month, 2023",
      unit: "k",
      x_label: "Sport",
      y_label: "Participants (thousands)",
      categories: ["Football", "Swimming", "Tennis", "Cycling", "Yoga", "Climbing"],
      series: [{ name: "Participants", values: [18, 12, 6, 9, 14, 3] }],
    },
  ),
  report(
    "education",
    6,
    "The bar chart below shows what school leavers in one country were doing one year after finishing secondary school in 2022.",
    {
      kind: "bar",
      title: "Destinations of school leavers one year after leaving school, 2022",
      unit: "%",
      y_label: "Share of school leavers (%)",
      categories: ["University", "College", "Employment", "Training", "Gap year", "Other"],
      series: [{ name: "School leavers", values: [41, 18, 20, 11, 6, 4] }],
    },
  ),
  report(
    "environment",
    6,
    "The bar chart below shows the average amount of food, in kilograms, thrown away per household in eight cities in 2023.",
    {
      kind: "bar",
      title: "Food thrown away per household, 2023",
      unit: "kg",
      x_label: "City",
      y_label: "Food waste per household (kg)",
      categories: ["City A", "City B", "City C", "City D", "City E", "City F", "City G", "City H"],
      series: [{ name: "Food waste", values: [95, 120, 74, 138, 62, 101, 88, 110] }],
    },
  ),
  report(
    "work",
    7,
    "The bar chart below shows the average number of hours worked per week by full-time employees in nine occupations in one country in 2023.",
    {
      kind: "bar",
      title: "Average weekly working hours by occupation, 2023",
      unit: "h",
      y_label: "Hours per week",
      categories: [
        "Doctors",
        "Farmers",
        "Lawyers",
        "Teachers",
        "Chefs",
        "Drivers",
        "Engineers",
        "Nurses",
        "Clerks",
      ],
      series: [{ name: "Hours per week", values: [48, 52, 46, 44, 47, 45, 41, 39, 37] }],
    },
  ),
  report(
    "technology",
    5,
    "The bar chart below shows the average number of minutes per day that teenagers in one country spent on five screen-based activities in 2024.",
    {
      kind: "bar",
      title: "Teenagers' daily screen time by activity, 2024",
      unit: "min",
      y_label: "Minutes per day",
      categories: ["Social media", "Video", "Gaming", "Homework", "Messaging"],
      series: [{ name: "Minutes per day", values: [118, 95, 64, 41, 37] }],
    },
  ),
  report(
    "health",
    6,
    "The bar chart below shows the average time, in minutes, that patients waited before being seen at the emergency departments of seven hospitals in one region in 2023.",
    {
      kind: "bar",
      title: "Average emergency department waiting times, 2023",
      unit: "min",
      x_label: "Hospital",
      y_label: "Waiting time (minutes)",
      categories: [
        "Riverside",
        "Northgate",
        "Parkview",
        "Hillcrest",
        "Millbrook",
        "Eastfield",
        "Westgate",
      ],
      series: [{ name: "Waiting time", values: [42, 95, 61, 128, 54, 77, 36] }],
    },
  ),
  report(
    "economy",
    7,
    "The bar chart below shows the percentage increase in the price of eight everyday goods and services in one country between 2021 and 2024.",
    {
      kind: "bar",
      title: "Price increases for everyday goods and services, 2021–2024",
      unit: "%",
      y_label: "Price increase (%)",
      categories: ["Bread", "Milk", "Eggs", "Coffee", "Petrol", "Rent", "Electricity", "Bus fare"],
      series: [{ name: "Price increase", values: [28, 34, 52, 41, 19, 23, 67, 12] }],
    },
  ),
];

// ---- Grouped bar charts ----------------------------------------------------

const GROUPED_BAR: StarterPrompt[] = [
  report(
    "food",
    5,
    "The chart below shows the number of portions of four meals sold in a university canteen during the autumn and spring terms of 2023.",
    {
      kind: "grouped_bar",
      title: "Portions sold in a university canteen by term, 2023",
      x_label: "Meal",
      y_label: "Portions sold",
      categories: ["Pasta", "Salad", "Burgers", "Curry"],
      series: [
        { name: "Autumn term", values: [4200, 2100, 3900, 3100] },
        { name: "Spring term", values: [3800, 3400, 3200, 2900] },
      ],
    },
  ),
  report(
    "transport",
    6,
    "The chart below shows the percentage of commuters who travelled to work in five different ways in a medium-sized town in 2004 and 2024.",
    {
      kind: "grouped_bar",
      title: "How commuters travelled to work, 2004 and 2024",
      unit: "%",
      x_label: "Way of travelling",
      y_label: "Share of commuters (%)",
      categories: ["Car", "Bus", "Train", "Bicycle", "On foot"],
      series: [
        { name: "2004", values: [58, 17, 9, 4, 12] },
        { name: "2024", values: [44, 15, 14, 16, 11] },
      ],
    },
  ),
  report(
    "education",
    7,
    "The chart below shows the percentage of students who achieved the highest grade in four subjects at three secondary schools in 2023.",
    {
      kind: "grouped_bar",
      title: "Students achieving the highest grade by subject, 2023",
      unit: "%",
      x_label: "Subject",
      y_label: "Students with the highest grade (%)",
      categories: ["Maths", "Science", "English", "History"],
      series: [
        { name: "Hillside School", values: [34, 29, 22, 18] },
        { name: "Oakfield School", values: [21, 25, 31, 27] },
        { name: "Brookside School", values: [28, 19, 26, 33] },
      ],
    },
  ),
  report(
    "technology",
    8,
    "The chart below shows the percentage of people in four age groups who used three types of online service in one country in 2024.",
    {
      kind: "grouped_bar",
      title: "Use of online services by age group, 2024",
      unit: "%",
      x_label: "Age group",
      y_label: "Users (%)",
      categories: ["16–24", "25–44", "45–64", "65+"],
      series: [
        { name: "Video calls", values: [92, 88, 71, 52] },
        { name: "Online shopping", values: [81, 90, 76, 43] },
        { name: "Online banking", values: [64, 85, 78, 49] },
      ],
    },
  ),
  report(
    "food",
    6,
    "The chart below shows the amount of wheat, rice and maize, in million tonnes, produced in three regions of one country in 2023.",
    {
      kind: "grouped_bar",
      title: "Grain production by region, 2023 (million tonnes)",
      x_label: "Region",
      y_label: "Production (million tonnes)",
      categories: ["Northern", "Central", "Southern"],
      series: [
        { name: "Wheat", values: [8.4, 5.1, 1.2] },
        { name: "Rice", values: [0.6, 3.8, 9.7] },
        { name: "Maize", values: [2.9, 6.3, 4.1] },
      ],
    },
  ),
  report(
    "education",
    6,
    "The chart below shows how many hours per week full-time university students in one country spent on four activities in 2003 and 2023.",
    {
      kind: "grouped_bar",
      title: "Students' weekly hours by activity, 2003 and 2023",
      unit: "h",
      x_label: "Activity",
      y_label: "Hours per week",
      categories: ["Studying", "Paid work", "Leisure", "Commuting"],
      series: [
        { name: "2003", values: [34, 6, 22, 4] },
        { name: "2023", values: [27, 15, 19, 3] },
      ],
    },
  ),
  report(
    "tourism",
    7,
    "The chart below shows the number of domestic and international visitors, in millions, to five regions of one country in 2023.",
    {
      kind: "grouped_bar",
      title: "Domestic and international visitors by region, 2023",
      unit: "m",
      x_label: "Region",
      y_label: "Visitors (millions)",
      categories: ["North", "South", "East", "West", "Capital"],
      series: [
        { name: "Domestic", values: [4.2, 6.8, 3.1, 2.5, 5.9] },
        { name: "International", values: [1.1, 2.4, 0.8, 0.6, 7.3] },
      ],
    },
  ),
  report(
    "health",
    8,
    "The chart below shows the percentage of adults in four regions of one country who met official guidelines for diet, physical activity and sleep in 2024.",
    {
      kind: "grouped_bar",
      title: "Adults meeting health guidelines by region, 2024",
      unit: "%",
      x_label: "Region",
      y_label: "Adults meeting the guideline (%)",
      categories: ["Region A", "Region B", "Region C", "Region D"],
      series: [
        { name: "Diet (fruit and vegetables)", values: [38, 29, 44, 25] },
        { name: "Physical activity", values: [55, 48, 51, 39] },
        { name: "Sleep", values: [62, 70, 58, 66] },
      ],
    },
  ),
  report(
    "media",
    5,
    "The chart below shows the number of people, in millions, who watched films at the cinema and on streaming services in one country in 2015, 2019 and 2023.",
    {
      kind: "grouped_bar",
      title: "People watching films at the cinema and on streaming services",
      unit: "m",
      x_label: "Year",
      y_label: "Viewers (millions)",
      categories: ["2015", "2019", "2023"],
      series: [
        { name: "Cinema", values: [42, 45, 24] },
        { name: "Streaming", values: [8, 21, 49] },
      ],
    },
  ),
];

// ---- Pie charts ------------------------------------------------------------

const PIE: StarterPrompt[] = [
  report(
    "leisure",
    5,
    "The pie chart below shows how university students in one country spent their free time on an average weekday in 2023.",
    {
      kind: "pie",
      title: "How students spent their free time on a weekday, 2023",
      unit: "%",
      slices: [
        { label: "Social media", value: 27 },
        { label: "Seeing friends", value: 21 },
        { label: "Watching TV", value: 18 },
        { label: "Sport", value: 14 },
        { label: "Gaming", value: 12 },
        { label: "Reading", value: 8 },
      ],
    },
  ),
  report(
    "environment",
    5,
    "The pie chart below shows how water is used in an average home in one country.",
    {
      kind: "pie",
      title: "Household water use by activity",
      unit: "%",
      slices: [
        { label: "Showers and baths", value: 31 },
        { label: "Toilets", value: 24 },
        { label: "Kitchen and bathroom taps", value: 18 },
        { label: "Washing machine", value: 15 },
        { label: "Garden", value: 7 },
        { label: "Dishwasher", value: 5 },
      ],
    },
  ),
  report(
    "work",
    6,
    "The pie chart below shows the main reasons employees gave for leaving a large company in 2023.",
    {
      kind: "pie",
      title: "Reasons employees gave for leaving the company, 2023",
      unit: "%",
      slices: [
        { label: "Better pay elsewhere", value: 31 },
        { label: "Lack of promotion", value: 19 },
        { label: "Long working hours", value: 16 },
        { label: "Poor management", value: 14 },
        { label: "Moving to another area", value: 9 },
        { label: "Retirement", value: 7 },
        { label: "Other", value: 4 },
      ],
    },
  ),
  report(
    "government",
    7,
    "The pie chart below shows how a city council spent its annual budget of $480 million in 2024.",
    {
      kind: "pie",
      title: "City council spending, 2024 (total budget $480 million)",
      unit: "%",
      slices: [
        { label: "Education", value: 29 },
        { label: "Social care", value: 24 },
        { label: "Transport", value: 14 },
        { label: "Housing", value: 11 },
        { label: "Police and safety", value: 9 },
        { label: "Waste and parks", value: 8 },
        { label: "Administration", value: 5 },
      ],
    },
  ),
  report(
    "environment",
    8,
    "The pie chart below shows the share of one country's food-related greenhouse gas emissions produced at each stage of the food supply chain in 2023.",
    {
      kind: "pie",
      title: "Food-related greenhouse gas emissions by stage of the supply chain, 2023",
      unit: "%",
      slices: [
        { label: "Farming", value: 42 },
        { label: "Clearing land for farming", value: 18 },
        { label: "Household food waste", value: 13 },
        { label: "Processing", value: 9 },
        { label: "Transport", value: 7 },
        { label: "Packaging", value: 6 },
        { label: "Shops and supermarkets", value: 5 },
      ],
    },
  ),
];

// ---- Tables ----------------------------------------------------------------

const TABLE: StarterPrompt[] = [
  report(
    "education",
    6,
    "The table below shows the number of international students, in thousands, studying at universities in four countries in 2013, 2018 and 2023.",
    {
      kind: "table",
      title: "International students at universities (thousands)",
      unit: "k",
      columns: ["Country", "2013", "2018", "2023"],
      rows: [
        ["Country A", 62, 85, 110],
        ["Country B", 140, 152, 138],
        ["Country C", 25, 48, 91],
        ["Country D", 88, 90, 94],
      ],
    },
  ),
  report(
    "transport",
    7,
    "The table below gives information about four airports in one country in 2023: the number of passengers, the number of destinations served and the average delay per flight.",
    {
      kind: "table",
      title: "Four airports compared, 2023",
      columns: ["Airport", "Passengers (millions)", "Destinations", "Average delay (minutes)"],
      rows: [
        ["Airport A", 38.5, 210, 14],
        ["Airport B", 12.1, 85, 9],
        ["Airport C", 24.7, 140, 22],
        ["Airport D", 4.3, 31, 6],
      ],
    },
  ),
  report(
    "economy",
    8,
    "The table below shows how families in three income groups in one country divided their household spending in 2023.",
    {
      kind: "table",
      title: "Household spending by income group, 2023 (% of total spending)",
      unit: "%",
      columns: ["Spending", "Low income", "Middle income", "High income"],
      rows: [
        ["Housing", 38, 30, 24],
        ["Food", 24, 16, 10],
        ["Transport", 11, 14, 13],
        ["Leisure", 5, 11, 17],
        ["Savings", 2, 9, 21],
        ["Other", 20, 20, 15],
      ],
    },
  ),
  report(
    "culture",
    5,
    "The table below shows the number of visitors, in thousands, to four museums in one city in 2019, 2021 and 2023.",
    {
      kind: "table",
      title: "Museum visitors (thousands)",
      unit: "k",
      columns: ["Museum", "2019", "2021", "2023"],
      rows: [
        ["Science Museum", 820, 410, 760],
        ["Art Gallery", 540, 300, 610],
        ["History Museum", 390, 220, 350],
        ["Toy Museum", 120, 95, 180],
      ],
    },
  ),
  report(
    "health",
    7,
    "The table below shows the average life expectancy at birth, in years, of men and women in four countries in 1970 and 2020.",
    {
      kind: "table",
      title: "Life expectancy at birth (years), 1970 and 2020",
      columns: ["Country", "Men, 1970", "Women, 1970", "Men, 2020", "Women, 2020"],
      rows: [
        ["Country A", 66, 72, 79, 83],
        ["Country B", 58, 61, 71, 76],
        ["Country C", 49, 52, 64, 69],
        ["Country D", 68, 74, 77, 82],
      ],
    },
  ),
  report(
    "technology",
    6,
    "The table below shows the percentage of sales made online by five types of shop in one country in 2014 and 2024.",
    {
      kind: "table",
      title: "Share of sales made online, by type of shop (%)",
      unit: "%",
      columns: ["Type of shop", "2014", "2024"],
      rows: [
        ["Clothing", 12, 38],
        ["Electronics", 21, 52],
        ["Groceries", 3, 14],
        ["Books", 29, 61],
        ["Furniture", 6, 23],
      ],
    },
  ),
];

export const CURATED_TASK1_ACADEMIC: StarterPrompt[] = [
  ...LINE,
  ...BAR,
  ...GROUPED_BAR,
  ...PIE,
  ...TABLE,
];
