-- ============================================================================
-- 20260702120000_listening.sql
-- IELTS Listening — AI-generated original parts (Parts 1 & 4 first) with
-- exam-style TTS audio. Items are generated by the IELTS AI Engine, which also
-- synthesizes the audio (Gemini TTS) and uploads per-segment MP3s to the
-- private `listening-audio` storage bucket.
--
-- Mirrors 20260628120000_multilevel.sql exactly:
--   * `content` holds the FULL item (script, answer key, trap ids, audio
--     manifest). Written with the service-role key by the engine; the browser
--     only ever receives the answer-stripped render view + signed audio URLs.
--   * Grading is by id server-side; RLS below is defense-in-depth + lets a
--     future Activities page list the learner's own attempts.
--
-- Idempotent: safe to re-run in the Supabase SQL editor.
-- ============================================================================

-- ---------- listening_items : one generated listening part (or future test) --
create table if not exists public.listening_items (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  student_id      uuid not null,
  scope           text not null default 'part',         -- 'part' | 'test' (later)
  part            int,                                  -- 1|2|3|4; null for a full test
  topic           text not null default '',
  -- Full generated item WITH the answer key + audio segment manifest
  -- ({kind:'audio',path}|{kind:'pause',seconds}). Storage paths only — URLs are
  -- signed per request by the engine.
  content         jsonb not null,
  created_at      timestamptz not null default now(),
  unique (id, organization_id),
  foreign key (student_id, organization_id)
    references public.profiles (id, organization_id) on delete cascade
);
create index if not exists listening_items_org_student_idx
  on public.listening_items (organization_id, student_id);
create index if not exists listening_items_created_idx
  on public.listening_items (created_at desc);

-- ---------- listening_attempts : one grading event against an item ----------
create table if not exists public.listening_attempts (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null,
  student_id      uuid not null,
  item_id         uuid not null,
  -- { "1": "Barker", "2": "garden", ... }
  user_answers    jsonb not null default '{}'::jsonb,
  -- Per-question verdicts + transcript reveal (what the review screen shows).
  result          jsonb not null default '{}'::jsonb,
  score           int,
  max_score       int,
  created_at      timestamptz not null default now(),
  foreign key (student_id, organization_id)
    references public.profiles (id, organization_id) on delete cascade,
  foreign key (item_id, organization_id)
    references public.listening_items (id, organization_id) on delete cascade
);
create index if not exists listening_attempts_org_student_idx
  on public.listening_attempts (organization_id, student_id);
create index if not exists listening_attempts_item_idx
  on public.listening_attempts (item_id);

-- ---------- Row Level Security ----------------------------------------------
alter table public.listening_items    enable row level security;
alter table public.listening_attempts enable row level security;

drop policy if exists listening_items_select on public.listening_items;
create policy listening_items_select on public.listening_items
  for select to authenticated
  using (
    organization_id = (select public.current_org_id())
    and student_id = (select auth.uid())
  );
drop policy if exists listening_items_insert on public.listening_items;
create policy listening_items_insert on public.listening_items
  for insert to authenticated
  with check (
    organization_id = (select public.current_org_id())
    and student_id = (select auth.uid())
  );
drop policy if exists listening_items_delete on public.listening_items;
create policy listening_items_delete on public.listening_items
  for delete to authenticated
  using (
    organization_id = (select public.current_org_id())
    and student_id = (select auth.uid())
  );

drop policy if exists listening_attempts_select on public.listening_attempts;
create policy listening_attempts_select on public.listening_attempts
  for select to authenticated
  using (
    organization_id = (select public.current_org_id())
    and student_id = (select auth.uid())
  );
drop policy if exists listening_attempts_insert on public.listening_attempts;
create policy listening_attempts_insert on public.listening_attempts
  for insert to authenticated
  with check (
    organization_id = (select public.current_org_id())
    and student_id = (select auth.uid())
  );
drop policy if exists listening_attempts_delete on public.listening_attempts;
create policy listening_attempts_delete on public.listening_attempts
  for delete to authenticated
  using (
    organization_id = (select public.current_org_id())
    and student_id = (select auth.uid())
  );

-- ---------- Grants ----------------------------------------------------------
grant select, insert, delete on public.listening_items    to authenticated;
grant select, insert, delete on public.listening_attempts to authenticated;
grant all on public.listening_items    to service_role;
grant all on public.listening_attempts to service_role;

-- ---------- Storage bucket for TTS audio -------------------------------------
-- Private: the engine uploads with the service-role key and hands the browser
-- short-lived signed URLs; no storage RLS policies for `authenticated` needed.
insert into storage.buckets (id, name, public)
values ('listening-audio', 'listening-audio', false)
on conflict (id) do nothing;
